### ISSUE TITLE
합동세미나 회고

### ISSUE THREAD

**Issue by daehwan2yo** [SOPTMON/AOS_SOPTMON#4]
## 구현
- [ ] FragmentContainer
  - [ ] 하나의 Activity 에서 여러명이 Fragment 를 각자 작업해서 합치는 경우 고려해봐야할 점은 무엇인가?
- [ ] 내부에서 정적으로 다루어지는 값들에 대해 한 곳에서 몰아서 일괄적으로 관리할 수 있는 포인트를 구성하면 어떨까?
   - 정적으로 각각 관리하는 경우 변경이 있을 경우 휴먼에러 발생할 가능성이 있을것같다. -> 유지 보수의 어려움?
<img width="442" alt="스크린샷 2022-11-26 오전 1 37 18" src="https://user-images.githubusercontent.com/26921986/204026788-6ce63ef2-a918-40f8-b631-87825670d5ee.png">

- [ ] Fragment 내에서 다른 Fragment 로의 이동
  - [ ] 상위 Activity 에서 처리가 필요할텐데, 이 과정이 어떻게 이루어지고 구현은 어떻게 해야할지
- [ ] ConstraintLayout 구현에 대한 이해
  - [ ] 각 컴포넌트간 상대적 위치 구분
- [ ] design custom

## Else
- [ ] android 프로젝트 구성
  - [ ] ignore 의 대상은 무엇인가?
  - [ ] 최초 세팅은 어떻게 하면 좋은가?
    - [ ] kotlin version
    - [ ] jdk version
    - [ ] gradle version
      - [ ] android studio version 에 영향을 받게 되는 것 같다. 
- [ ] 패키지 구조는 어떻게 가져가면 좋을까?
  - [ ] MVC or MVVM
    - [ ] android 구조에서 많이 활용되어지는 디자인 패턴은 무엇일까?
      - [ ] MVVM 에 대해서 더 공부해보자
- [ ] 용어 정리 필요
  - [ ] 디자인 및 안드로이드 UI 용어에 대한 정리가 필요할것같다.
  - [ ] 안드로이드 구현시 좀 더 다양하고 참신한 네이밍이 없을까?

## Todo
- [ ] Template 구성
  - [ ] Fragment
  - [ ] Adapter
  - [ ] Api (for network)
- [ ] Factory?
  - [ ] Data
